In [1]:
import numpy as np


In [2]:
import numpy as np
print(np.__version__)

1.18.5


In [5]:
#function_1
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
#function_2
a.shape

(3, 5)

In [7]:
#function_3
a.ndim

2

In [8]:
#functon_4
a.dtype.name

'int64'

In [9]:
#functon_5
a.itemsize

8

In [10]:
#functon_6
a.size

15

In [11]:
#functon_7

a.item

<function ndarray.item>

In [12]:
#functon_8
type(a)

numpy.ndarray

In [13]:
#functon_9
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [15]:
#functon_10
a = np.array([2, 3, 4])
 
a, type(a), a.dtype

(array([2, 3, 4]), numpy.ndarray, dtype('int64'))

In [16]:
#functon_11
b = np.array([2.5, 3.8, 4.3])
 
b, type(b), b.dtype

(array([2.5, 3.8, 4.3]), numpy.ndarray, dtype('float64'))

In [17]:
#functon_12
b = np.array([(1.5, 3, 3), (4, 6, 8)])

b, b.dtype

(array([[1.5, 3. , 3. ],
        [4. , 6. , 8. ]]),
 dtype('float64'))

In [18]:
#functon_13
c = np.array([[1,2], [3,4]], dtype=complex)

c


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
#functon_14
d = np.zeros((3, 4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#functon_15
np.ones((2, 5, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [21]:
#functon_16
np.empty((2, 5))


array([[4.64346626e-310, 2.33419537e-312, 2.46151512e-312,
        2.35541533e-312, 2.01589600e-312],
       [2.12199579e-313, 9.76118064e-313, 2.20687562e-312,
        2.37663529e-312, 1.33360289e+241]])

In [23]:
#functon_17
np.arange(10, 30, 5)
          

array([10, 15, 20, 25])

In [24]:
#functon_18
np.arange(.5, 15, 3)

array([ 0.5,  3.5,  6.5,  9.5, 12.5])

In [25]:
#functon_19
from numpy import pi

np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
#functon_20
x = np.linspace(0, 2*pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [27]:
#functon_21
f = np.sin(x)
f


array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [28]:
#functon_22
np.empty_like((4, 6))

array([-9093133594791772939,      140362266591128])

In [29]:
#functon_23
np.ones_like((3, 8))

array([1, 1])

In [30]:
#functon_24
np.zeros_like((2, 8))

array([0, 0])

In [31]:
#functon_25
a = np.array([20, 30, 0, 50])
b = np.arange(4)

a, b

(array([20, 30,  0, 50]), array([0, 1, 2, 3]))

In [32]:
#functon_26
b**2

array([0, 1, 4, 9])

In [33]:
#functon_27
10*np.sin(a)

array([ 9.12945251, -9.88031624,  0.        , -2.62374854])

In [34]:
#functon_28
a>35, a

(array([False, False, False,  True]), array([20, 30,  0, 50]))

In [35]:
#functon_29
A = np.array([[1,1],
             [0,1]])
B = np.array([[3,4],
             [0,8]])

A*B

array([[3, 4],
       [0, 8]])

In [36]:
#functon_30
A @ B

array([[ 3, 12],
       [ 0,  8]])

In [37]:
#functon_31
A.dot(B)

array([[ 3, 12],
       [ 0,  8]])

In [38]:
#functon_32
rg = np.random.default_rng(1)

a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))

a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [39]:
#functon_33
b += a

b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [40]:
#functon_34
b = np.linspace(0, pi, 3)

b.dtype.name

'float64'

In [41]:
#functon_35
c = a+b

c

array([[3.        , 4.57079633, 6.14159265],
       [3.        , 4.57079633, 6.14159265]])

In [42]:
#functon_36
d = np.exp(c*1j)

d

array([[-0.9899925 +0.14112001j, -0.14112001-0.9899925j ,
         0.9899925 -0.14112001j],
       [-0.9899925 +0.14112001j, -0.14112001-0.9899925j ,
         0.9899925 -0.14112001j]])

In [43]:
#functon_37
d.dtype.name

'complex128'

In [44]:
#functon_38
a = rg.random((2, 3))
a


array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [45]:
#functon_39
a.sum()

3.1057109529998157

In [46]:
#functon_40
a.min()

0.027559113243068367

In [47]:
#functon_41
a.max()


0.8277025938204418

In [48]:
#functon_42
b = np.arange(12).reshape(3, 4)
b.sum(axis=0)

array([12, 15, 18, 21])

In [49]:
#functon_43
b.min(axis=1)

array([0, 4, 8])

In [50]:
#functon_44
b.cumsum(axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [51]:
#functon_45
B = np.arange(3)
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [52]:
#functon_46
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [53]:
#functon_47
C = np.array([1, 5, 6])

np.add(B, C)

array([1, 6, 8])

In [54]:
#functon_48
np.all(B)

False

In [55]:
#functon_49
np.average(B)

1.0

In [56]:
#functon_50
np.sort(B)

array([0, 1, 2])